Send Silently config option for Telegram messages.
eone666/telegram-notifier pull request #4
Opened 2023-06-11 16:57 UTC by kkroboth

Love the plugin! I wanted the notifications to be silent on my phone and you can do that by using the `disable_notification` API prop. https://core.telegram.org/bots/api#sendmessage

* The `baseOptions`, chatId and sendSilently are remove from the send, edit, and pin method parameters as they are common. I updated the constructor to include those additional params.
* Refactored away from using anonymous HashMaps and added a baseOptions for common telegram API properties.
* Updated README to include new sendSilently config option

I noticed you were initializing HashMaps with the anonymous class style. This can cause unnoticed side effects outlined in this [blog](https://blog.jooq.org/dont-be-clever-the-double-curly-braces-anti-pattern/).

I just converted them to use Kotlin's immutable maps and mutable maps were applicable, but happy to revert those changes if you want this PR to just adding the send silently prop.

2023-06-23 18:40 UTC, eone666 commented
also need to add these new property to /src/main/resources/config.yml

2023-06-23 18:42 UTC, eone666 commented
sorry for the long answer, unfortunately I don't have time to support this project yet, but the project is not abandoned and I'm going to develop it in the future

2023-06-28 11:06 UTC, eone666 requested changes

2023-06-28 11:06 UTC, eone666 commented on src/main/kotlin/io/github/eone666/telegramnotifier/utils/telegram/Telegram.kt
> +class Telegram(token: String, chatId: String, sendSilently: Boolean) {
the idea of `Telegram` class is just telegram client, that doesnt include any plugin specific logic.Its made for future replacement to third-party telegram library

2023-06-28 21:19 UTC, kkroboth commented
> sorry for the long answer, unfortunately I don't have time to support this project yet, but the project is not abandoned and I'm going to develop it in the future

Gotcha! Ya. I'm on vacation right now and I'll make the changes you requested when I get back in a couple days.

2023-07-03 07:16 UTC, eone666 approved these changes
that's better

2023-07-03 07:17 UTC, merged

2023-07-03 07:30 UTC, eone666 commented
@kkroboth thanks for contributing to the project